src/educacao/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'educacao'

urlpatterns = [
    path(
        '',
        login_required(views.Index.as_view()),
        name='index'
    ),
    path(
        '<int:id_disciplina>',
        login_required(views.Index.as_view()),
        name='index'
    ),
    path(
        'criar/disciplina/',
        login_required(views.CriarDisciplina.as_view()),
        name='criar_disciplina'
    ),
    path(
        'inscrever/disciplina/<int:id_disciplina>/',
        login_required(views.InscreverNaDisciplina.as_view()),
        name='matricular_na_disciplina'
    ),
    path(
        'editar/disciplina/<int:id_disciplina>/',
        (views.EditarDisciplina.as_view()),
        name='editar_disciplina'
    ),
    path(
        'ver/disciplina/<int:id_disciplina>/',
        login_required(views.VerDisciplina.as_view()),
        name='ver_disciplina'
    ),
    path(
        'ver/aula/<int:id_aula>/',
        login_required(views.VerAula.as_view()),
        name='ver_aula'
    ),
    path(
        'editar/aula/<int:id_aula>/',
        login_required(views.EditarAula.as_view()),
        name='editar_aula'
    ),
    path(
        'criar/artigo/<int:id_aula>/',
        login_required(views.CriarArtigo.as_view()),
        name='criar_artigo'
    ),
    path(
        'editar/artigo/<int:id_artigo>/',
        login_required(views.EditarArtigo.as_view()),
        name='editar_artigo'
    ),
    path(
        'ver/artigo/<int:id_artigo>/',
        login_required(views.VerArtigo.as_view()),
        name='ver_artigo'
    ),
    path(
        'criar/lista-exercicios/disciplina/<int:id_disciplina>/',
        login_required(views.CriarListaExercicios.as_view()),
        name='criar_lista_exercicios'
    ),
    path(
        'criar/relatorio/disciplina/<int:id_disciplina>/',
        login_required(views.CriarRelatorio.as_view()),
        name='criar_relatorio'
    ),
    path(
        'editar/relatorio/<int:id_relatorio>/',
        login_required(views.EditarRelatorio.as_view()),
        name='editar_relatorio'
    ),
    path(
        'responder/relatorio/<int:id_relatorio>/',
        login_required(views.ResponderRelatorio.as_view()),
        name='responder_relatorio'
    ),
    path(
        'criar/experimento/relatorio/<int:id_relatorio>/',
        login_required(views.AdicionarExperimentoRemotoNoRelatorio.as_view()),
        name='adicionar_experimento_remoto_no_relatorio'
    ),
    path(
        'remover/experimento/relatorio/<int:id_experimento>/',
        login_required(views.RemoverExperimentoNoLabRemoto.as_view()),
        name='remover_experimento_remoto_no_relatorio'
    ),
    path(
        'ver/experimento/<int:id_experimento>/',
        login_required(views.VerExperimento.as_view()),
        name='ver_experimento'
    ),
    path(
        'criar/execucao/<int:id_experimento>/',
        login_required(views.CriarExecucao.as_view()),
        name='criar_execucao'
    ),
    path(
        'duplicar/execucao/<int:id_experimento>/<int:id_execucao>/',
        login_required(views.DuplicarExecucao.as_view()),
        name='duplicar_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.VerExecucao.as_view()),
        name='ver_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/codigo/',
        login_required(views.VerCodigoExecucao.as_view()),
        name='ver_codigo_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/grafico/',
        login_required(views.VerGrafico.as_view()),
        name='ver_grafico'
    ),
    path(
        'criar/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.EditarExecucao.as_view()),
        name='editar_execucao'
    ),
    path(
        'executar/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.ExecutarExperimento.as_view()),
        name='executar_experimento'
    ),
    path(
        'configurar/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarConfiguracoesAvaliacao.as_view()),
        name='editar_configuracoes_avaliacao'
    ),
    path(
        'editar/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarQuestaoAvaliacao.as_view()),
        name='editar_questao_avaliacao'
    ),
    path(
        'editar/questao/<int:id_questao_avaliacao>/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarQuestaoAvaliacao.as_view()),
        name='editar_questao_avaliacao'
    ),
    path(
        'editar/avaliacao/<int:id_avaliacao>/criar-nova-questao/',
        login_required(views.AdicionarQuestaoNaAvaliacao.as_view()),
        name='adicionar_questao_avaliacao'
    ),
    path(
        'editar/remover-questao/<int:id_questao_avaliacao>/',
        login_required(views.RemoverQuestaoAvaliacao.as_view()),
        name='remover_questao_avaliacao'
    ),
    path(
        'editar/questao/<int:id_questao_avaliacao>/criar-nova-alternativa/',
        login_required(views.AdicionarAlternativaNaQuestaoDaLista.as_view()),
        name='adicionar_alternativa_questao_avaliacao'
    ),
    path(
        'responder/lista-exercicios/<int:id_avaliacao>/',
        login_required(views.ResponderQuestaoListaExercicios.as_view()),
        name='responder_questao_da_avaliacao'
    ),
    path(
        'responder/questao/<int:id_questao_avaliacao>/lista-exercicios/<int:id_avaliacao>/',
        login_required(views.ResponderQuestaoListaExercicios.as_view()),
        name='responder_questao_da_avaliacao'
    ),
    path(
        'adicionar/anexo/<str:onde>/<int:id>/',
        login_required(views.AdicionarAnexo.as_view()),
        name='adicionar_anexo_onde'
    ),
    path(
        'remover/anexo/<str:onde>/<int:id_anexo>/',
        login_required(views.RemoverAnexoOnde.as_view()),
        name='remover_anexo_onde'
    ),
    path(
        'ver/correcao/lista-exercicios/<int:id_lista>/',
        login_required(views.VerCorrecaoAvaliacao.as_view()),
        name='ver_correcao_lista_exercicios'
    ),
    path(
        'ver/entregas/avaliacao/<int:id_avaliacao>/',
        login_required(views.VerEntregasAvaliacao.as_view()),
        name='ver_entregas_avaliacao'
    ),
    path(
        'corrigir/avaliacao/<int:id_avaliacao>/aluno/<int:id_aluno>/',
        login_required(views.CorrigirQuestaoAvaliacao.as_view()),
        name='corrigir_avaliacao_aluno'
    ),
]

src/lab_remoto/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'lab_remoto'

urlpatterns = [
    path(
        '',
        login_required(views.Index.as_view()),
        name='index'
    ),

    path(
        'criar/kit/',
        login_required(views.CriarKit.as_view()),
        name='criar_kit'
    ),

    path(
        'editar/kit/<int:id_kit>/',
        login_required(views.EditarKit.as_view()),
        name='editar_kit'
    ),

    path(
        'remover/kit/<int:id_kit>/',
        login_required(views.RemoverKit.as_view()),
        name='remover_kit'
    ),

    path(
        'criar/ensaio/',
        login_required(views.CriarEnsaio.as_view()),
        name='criar_ensaio'
    ),

    path(
        'remover/ensaio/<int:id_ensaio>/',
        login_required(views.RemoverEnsaio.as_view()),
        name='remover_ensaio'
    ),

    path(
        'editar/ensaio/<int:id_ensaio>/',
        login_required(views.EditarEnsaio.as_view()),
        name='editar_ensaio'
    ),

    path(
        'remover/parametro/<int:id_parametro>/',
        login_required(views.RemoverParametro.as_view()),
        name='remover_parametro'
    ),

    path(
        'editar/executar/ensaio/<int:id_ensaio>/',
        login_required(views.ExecutarEnsaio.as_view()),
        name='executar_ensaio'
    ),
]

src/sistema_gerenciamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('almoxarifado/', include('almoxarifado.urls')),
    path('educacao/', include('educacao.urls')),
    path('lab_remoto/', include('lab_remoto.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
    ]

src/educacao/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.forms import formset_factory

from .models import *
from usuarios.models import Usuario

try:
    from src.lab_remoto.models import ParametroInformado, ExecucaoEnsaio
except:
    from lab_remoto.models import ParametroInformado, ExecucaoEnsaio

class FormCriarDisciplina(forms.ModelForm):
    # Considerações sobre a criação de disciplinas
    # - as atividades avaliativas são criadas depois
    # - os criterios de avaliação serão preenchidos depois
    # - a bibliografia será inserida depois
    # - quando a disciplina é criada, ela não está aceitando matriculas
    class Meta:
        model = Disciplina
        exclude = (
            'data_criacao',
            'objetivo',
            'professor',
            'criterios_avaliacao',
            'bibliografia',
            'numero_provas',
            'numero_relatorios',
            'numero_trabalhos',
            'numero_listas',
            'numero_matriculas',
            'numero_seminarios',
            'aberto_para_inscricoes',
            'inscritos',
            'professores',
        )


class FormInscreverDisciplina(forms.Form):
    senha = forms.CharField(
        label='Senha',
        max_length=50
    )


class FormEditarDisciplina(forms.ModelForm):
    # Considerações sobre a criação de disciplinas
    # - a quantidade de atividades é gerenciada automaticamente
    class Meta:
        model = Disciplina
        exclude = (
            'data_criacao',
            'numero_aulas',
            'numero_provas',
            'numero_relatorios',
            'numero_trabalhos',
            'numero_listas',
            'numero_matriculas',
            'numero_seminarios',
            'inscritos',
        )

    def __init__(self, *args, **kwargs):
        super(FormEditarDisciplina, self).__init__(*args, **kwargs)
        self.fields['professores'].queryset = Usuario.objects.filter(tipo=Usuario.TIPO_DOCENTE)


class FormEditarAula(forms.ModelForm):
    class Meta:
        model = Aula
        exclude = ('data_criacao', )


class FormCriarArtigo(forms.ModelForm):
    class Meta:
        model = ArtigoAula
        exclude = ('aula', 'data_criacao',)


class FormEditarQuestao(forms.ModelForm):
    class Meta:
        model = Questao
        fields = ('nota_maxima', 'tipo', 'enunciado', )


class FormEditarAlternativaMultiplaEscolha(forms.ModelForm):
    class Meta:
        model = Alternativa
        fields = ('codigo', 'nota_maxima', 'enunciado', 'resposta_correta', 'feedback', )


FormsetEditarAlternativasMultiplaEscolha = forms.modelformset_factory(
    Alternativa,
    form=FormEditarAlternativaMultiplaEscolha,
    extra=0
)


class FormEditarAlternativaDissertativa(forms.ModelForm):
    class Meta:
        model = Alternativa
        fields = ('questao', 'codigo', 'enunciado', 'feedback', )


FormsetEditarAlternativasDissertativa = forms.modelformset_factory(
    Alternativa,
    form=FormEditarAlternativaDissertativa,
    extra=0
)


class FormEditarListaExercicios(forms.ModelForm):
    # Considerações sobre listas de exercícios
    # - uma avaliação não pode ser convertida em outra coisa (exemplo: prova -> trabalho)
    # - são sempre individuais

    class Meta:
        model = Avaliacao
        exclude = ('tipo', 'individual', 'numero_maximo_integrantes_grupo',)


class FormEditarRelatorio(forms.ModelForm):
    class Meta:
        model = Avaliacao
        exclude = (
            'tipo',
            'numero',
            'numero_questoes',
            'nota_maxima',
            'disciplina',
            'data_criacao',
            'correcao_automatica',
            'descontar_um_ponto_a_cada_n_erradas',
            'penalidade_por_dia_atraso',
            'individual',
        )


class FormFilmarExperimento(forms.ModelForm):
    class Meta:
        model = ExecucaoEnsaio
        fields = (
            'filmar',
        )

        labels = {
            'filmar': _('Sim eu quero filmar o experimento'),
        }


class FormEditarParametrosInformados(forms.ModelForm):
    class Meta:
        model = ParametroInformado
        fields = (
            'valor_informado',
        )


FormsetEditarParametrosInformados = forms.modelformset_factory(
    ParametroInformado,
    form=FormEditarParametrosInformados,
    extra=0
)


class FormCriarResposta(forms.ModelForm):
    class Meta:
        model = Resposta
        fields = ('resposta', 'questao', 'alternativa', )


FormsetCriarRespostaAlternativa = forms.modelformset_factory(
    Resposta,
    form=FormCriarResposta,
    extra=0
)


class FormEditarResposta(forms.ModelForm):
    class Meta:
        model = Resposta
        fields = ('resposta', )


FormsetEditarRespostaAlternativa = forms.modelformset_factory(
    Resposta,
    form=FormEditarResposta,
    extra=0
)


class FormEditarRespostaDissertativa(forms.ModelForm):
    class Meta:
        model = Resposta
        fields = ('conteudo',)


class FormEditarRespostaMultiplaEscolha(forms.ModelForm):
    class Meta:
        model = Resposta
        fields = ('resposta',)

        widgets = {
            'resposta': forms.RadioSelect()
        }

    def __init__(self, *args, **kwargs):
        self.opcoes = kwargs.pop('opcoes')
        super(FormEditarRespostaMultiplaEscolha, self).__init__(*args, **kwargs)
        self.fields['resposta'].choices = self.opcoes


FabricaEditarRespostaMultiplaEscolha = forms.modelformset_factory(
    Resposta,
    form=FormEditarRespostaMultiplaEscolha,
    extra=0
)


class FormsetEditarRespostaMultiplaEscolha(FabricaEditarRespostaMultiplaEscolha):
    def __init__(self, *args, **kwargs):
        #  create a user attribute and take it out from kwargs
        # so it doesn't messes up with the other formset kwargs
        self.opcoes = kwargs.pop('opcoes')
        super(FormsetEditarRespostaMultiplaEscolha, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False

    def _construct_form(self, *args, **kwargs):
        # inject user in each form on the formset
        kwargs['opcoes'] = self.opcoes
        return super(FormsetEditarRespostaMultiplaEscolha, self)._construct_form(*args, **kwargs)


class FormAdicionarAnexoResposta(forms.ModelForm):
    class Meta:
        model = AnexoResposta
        fields = ('resposta', 'nome_arquivo', 'tipo', 'arquivo',)

    def __init__(self, *args, **kwargs):
        self.ids_respostas = kwargs.pop('ids_respostas')
        super(FormAdicionarAnexoResposta, self).__init__(*args, **kwargs)
        self.fields['resposta'].queryset = Resposta.objects.filter(id__in=self.ids_respostas)


class FormAdicionarAnexoRelatorio(forms.ModelForm):
    class Meta:
        model = AnexoRelatorio
        fields = ('nome_arquivo', 'tipo', 'arquivo',)


class FormCorrigirResposta(forms.ModelForm):
    class Meta:
        model = Resposta
        fields = ('nota', 'feedback', )


FabricaCorrigirResposta = forms.modelformset_factory(
    Resposta,
    form=FormCorrigirResposta,
    extra=0
)

src/educacao/templates/educacao/ver_disciplina.html
{% extends "educacao/index.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block barra_horizontal %}
    <h3 class="text-light">Disciplina {{ disciplina.sigla }} ({{ disciplina.turma }})</h3>
{% endblock %}


{% block bibliotecas %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/educacao.css' %}">
{% endblock %}


{% block corpo_pagina %}
    <div class="container-fluid bg-light rounded-top">

    <p style="margin-top: 10px"></p>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#descricao" role="tab">
                Descrição
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#aulas" role="tab">
                Aulas
            </a>
        </li>
        {% if disciplina.numero_listas > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#listas-exercicios" role="tab">
                Séries de exercícios
            </a>
        </li>
        {% endif %}
        {% if disciplina.numero_trabalhos > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#trabalhos" role="tab">
                Trabalhos
            </a>
        </li>
        {% endif %}
        {% if disciplina.numero_relatorios > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#relatorios" role="tab">
                Relatórios
            </a>
        </li>
        {% endif %}
        {% if disciplina.numero_provas > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#provas" role="tab">
                Provas
            </a>
        </li>
        {% endif %}
        {% if disciplina.numero_seminarios > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#seminarios" role="tab">
                Seminários
            </a>
        </li>
        {% endif %}
    </ul>
    <div class="tab-content" id="myTabContent" style="margin-top: 10px">
        <div class="tab-pane fade show active" id="descricao" role="tabpanel">
            <div class="card cartao">
                <h5 class="card-header cartao-titulo">
                    Objetivos
                </h5>
                <div class="card-body">
                    {{ disciplina.objetivo|safe }}
                </div>
            </div>

            <div class="card cartao">
                <h5 class="card-header cartao-titulo">
                    Critérios de avaliação
                </h5>
                <div class="card-body">
                    {{ disciplina.criterios_avaliacao|safe }}
                </div>
            </div>

            <div class="card cartao">
                <h5 class="card-header cartao-titulo">
                    Bibliografia
                </h5>
                <div class="card-body">
                    {{ disciplina.bibliografia|safe }}
                </div>
            </div>
        </div>

        {#########}
        {# Aulas #}
        {#########}
        <div class="tab-pane fade" id="aulas" role="tabpanel">
            <table class="tabela-lista" id="tabela-aulas">
                <thead>
                    <tr>
                        <th>Ações</th>
                        <th>Número</th>
                        <th>Descrição</th>
                        <th>Data prevista</th>
                    </tr>
                </thead>
                <tbody>
                {% for aula in aulas %}
                    {% if aula.visivel or usuario in disciplina.professores.all %}
                        <tr>
                            <td>
                                <a href="{% url 'educacao:ver_aula' aula.id %}">
                                    <img src="{% static 'icones/ver.svg' %}" alt="Editar">
                                </a>
                                {% if usuario.tipo == usuario.TIPO_DOCENTE %}
                                <a href="{% url 'educacao:editar_aula' aula.id %}">
                                    <img src="{% static 'icones/editar.svg' %}" alt="Editar">
                                </a>
                                <a href="#">
                                    <img src="{% static 'icones/apagar.svg' %}" alt="Remover">
                                </a>
                                {% endif %}
                            </td>
                            <td>{{ aula.numero }}</td>
                            <td>{{ aula.descricao|safe }}</td>
                            <td>{{ aula.data_da_aula|date:"d/m/Y" }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>

        {% if usuario.tipo == usuario.TIPO_DOCENTE or disciplina.numero_listas > 0 %}
        <div class="tab-pane fade  tabela_maior" id="listas-exercicios" role="tabpanel">

            {% if usuario.tipo == usuario.TIPO_DOCENTE %}
                <a class="btn btn-secondary botao-barra-horizontal" href="{% url 'educacao:criar_lista_exercicios' disciplina.id %}">
                    <img src="{% static 'icones/novo.svg'%}" width="20px">
                    Adicionar nova lista de exercícios
                </a>
                <p></p>
            {% endif %}

            {% if disciplina.numero_listas > 0 %}
                <table class="tabela-lista" id="tabela-listas">
                    <thead>
                        <tr>
                            <th>Ações</th>
                            <th>Série de exercícios</th>
                            <th>Data limite para entrega</th>
                            <th>Corrigida?</th>
                            <th>Nota</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for lista in listas %}
                    {% if usuario.tipo == usuario.TIPO_DOCENTE or lista.visibilidade == lista.VISIBILIDADE_VISIVEL  %}
                    <tr>
                        <td>
                            <a href="{% url 'educacao:responder_questao_da_avaliacao' lista.id %}" data-toggle="tooltip" data-placement="bottom" title="Responder as questões">
                                <img src="{% static 'icones/ver.svg' %}" alt="Resolver">
                            </a>

                            {% if usuario.tipo == usuario.TIPO_DOCENTE %}
                                <a href="{% url 'educacao:ver_entregas_avaliacao' lista.id %}" data-toggle="tooltip" data-placement="bottom" title="Ver entregas">
                                    <img src="{% static 'icones/preview.svg' %}" alt="Ver entregas">
                                </a>
                                <a href="{% url 'educacao:editar_questao_avaliacao' lista.id %}"data-toggle="tooltip" data-placement="bottom" title="Editar questões">
                                    <img src="{% static 'icones/editar.svg' %}" alt="Editar questões">
                                </a>
                                <a href="{% url 'educacao:editar_configuracoes_avaliacao' lista.id %}"data-toggle="tooltip" data-placement="bottom" title="Configurar a lista de exercícios">
                                    <img src="{% static 'icones/engrenagens.svg' %}" alt="Editar configurações">
                                </a>
                            {% endif %}
                        </td>
                        <td>{{ lista.titulo }}</td>
                        <td>{{ lista.data_limite_entrega|date:"d/m/Y" }}</td>
                        <td>
                            {% if lista.corrigido %}
                                {% if lista.corrigido == True %}
                                <a href="{% url 'educacao:ver_correcao_lista_exercicios' lista.id %}">Ver correção</a>
                                {% else %}
                                    Não
                                {% endif %}
                            {% endif %}
                        </td>
                        <td>
                            {% if lista.mostrar_nota_apos_submissao %}
                                {{ lista.nota|floatformat:1 }}
                            {% else %}
                                {{ lista.nota|floatformat:1 }}
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                {# Não há nenhuma lista de exercícios cadastrada ainda! #}
            {% endif %}
        </div>
        {% endif %}

        {% if disciplina.numero_trabalhos > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <div class="tab-pane fade tabela_maior" id="trabalhos" role="tabpanel">
        </div>
        {% endif %}

        {################}
        {#  RELATORIOS  #}
        {################}

        {% if disciplina.numero_relatorios > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <div class="tab-pane fade tabela_maior" id="relatorios" role="tabpanel">
            {% if usuario.tipo == usuario.TIPO_DOCENTE %}
                <a class="btn btn-secondary botao-barra-horizontal" href="{% url 'educacao:criar_relatorio' disciplina.id %}">
                    <img src="{% static 'icones/novo.svg'%}" width="20px">
                    Adicionar novo relatório
                </a>
                <p></p>
            {% endif %}

            {% if disciplina.numero_relatorios > 0 %}
                <table class="tabela-lista" id="tabela-relatorios">
                    <thead>
                        <tr>
                            <th>Ações</th>
                            <th>Relatórios</th>

                            {% if usuario.tipo == usuario.TIPO_DOCENTE %} <th>Status</th> {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                    {% for relatorio in relatorios %}
                    {% if usuario.tipo == usuario.TIPO_DOCENTE or relatorio.visibilidade == relatorio.VISIBILIDADE_VISIVEL  %}
                    <tr>
                        <td>
                            <a href="{% url 'educacao:responder_relatorio' relatorio.id %}" data-toggle="tooltip" data-placement="bottom" title="Responder o relatório">
                                <img src="{% static 'icones/ver.svg' %}" alt="Responder o relatório">
                            </a>

                            {% if usuario.tipo == usuario.TIPO_DOCENTE %}
{#                                <a href="{% url 'educacao:ver_entregas_avaliacao' lista.id %}" data-toggle="tooltip" data-placement="bottom" title="Ver entregas">#}
{#                                    <img src="{% static 'icones/preview.svg' %}" alt="Ver entregas">#}
{#                                </a>#}
                                <a href="{% url 'educacao:editar_relatorio' relatorio.id %}"data-toggle="tooltip" data-placement="bottom" title="Editar relatório">
                                    <img src="{% static 'icones/editar.svg' %}" alt="Editar relatório">
                                </a>
{#                                <a href="{% url 'educacao:editar_configuracoes_avaliacao' lista.id %}"data-toggle="tooltip" data-placement="bottom" title="Configurar a lista de exercícios">#}
{#                                    <img src="{% static 'icones/engrenagens.svg' %}" alt="Editar configurações">#}
{#                                </a>#}
                            {% endif %}
                        </td>
                        <td>{{ relatorio.titulo }}</td>
                        {% if usuario.tipo == usuario.TIPO_DOCENTE %}
                            <td>
                                {% if relatorio.visibilidade == relatorio.VISIBILIDADE_OCULTO %}
                                    Oculto
                                {% elif relatorio.visibilidade == relatorio.VISIBILIDADE_VISIVEL_APOS_A_DATA %}
                                    Visível após a data {{ relatorio.data_para_ficar_visivel|date:"d/m/Y" }}
                                {% else %}
                                    Visível
                                {% endif %}
                            </td>
                        {% endif %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                {# Não há nenhuma lista de exercícios cadastrada ainda! #}
            {% endif %}
        </div>
        {% endif %}


        {% if disciplina.numero_provas > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <div class="tab-pane fade tabela_maior" id="provas" role="tabpanel">
        </div>
        {% endif %}

        {% if disciplina.numero_seminarios > 0 or usuario.tipo == usuario.TIPO_DOCENTE %}
        <div class="tab-pane fade tabela_maior" id="seminarios" role="tabpanel">
        </div>
        {% endif %}
    </div>

    </div>


{% endblock %}




{% block javascript %}
{% endblock %}