src/almoxarifado/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'almoxarifado'

urlpatterns = [
    path(
        '',
        views.Index.as_view(),
        name='index'
    ),
    path(
        'equipamentos/',
        views.IndexEquipamentos.as_view(),
        name='index_equipamentos'
    ),
    path(
        'equipamentos/criado/fabricante/<int:id_fabricante>/',
        views.IndexEquipamentos.as_view(),
        name='index_equipamentos'
    ),
    path(
        'equipamentos/criado/modelo/<int:id_modelo>/',
        views.IndexEquipamentos.as_view(),
        name='index_equipamentos'
    ),
    path(
        'equipamentos/criar/fabricante',
        views.CriarFabricante.as_view(),
        name='criar_fabricante'
    ),
    path(
        'equipamentos/ver/fabricantes',
        views.VerFabricantes.as_view(),
        name='ver_fabricantes'
    ),
    path(
        'equipamentos/editar/fabricante/<int:id_fabricante>',
        views.EditarFabricante.as_view(),
        name='editar_fabricante'
    ),
    path(
        'equipamentos/criar/modelo',
        views.CriarModelo.as_view(),
        name='criar_modelo'
    ),
    path(
        'equipamentos/ver/modelos',
        views.VerModelos.as_view(),
        name='ver_modelos'
    ),
    path(
        'equipamentos/editar/modelo/<int:id_modelo>',
        views.EditarModelo.as_view(),
        name='editar_modelo'
    ),
    path(
        'criar/tipo-de-item/',
        views.CriarTipoItem.as_view(),
        name='criar_tipo_item'
    ),
]

src/educacao/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'educacao'

urlpatterns = [
    path(
        '',
        login_required(views.Index.as_view()),
        name='index'
    ),
    path(
        '<int:id_disciplina>',
        login_required(views.Index.as_view()),
        name='index'
    ),
    path(
        'criar/disciplina/',
        login_required(views.CriarDisciplina.as_view()),
        name='criar_disciplina'
    ),
    path(
        'inscrever/disciplina/<int:id_disciplina>/',
        login_required(views.InscreverNaDisciplina.as_view()),
        name='matricular_na_disciplina'
    ),
    path(
        'editar/disciplina/<int:id_disciplina>/',
        (views.EditarDisciplina.as_view()),
        name='editar_disciplina'
    ),
    path(
        'ver/disciplina/<int:id_disciplina>/',
        login_required(views.VerDisciplina.as_view()),
        name='ver_disciplina'
    ),
    path(
        'ver/aula/<int:id_aula>/',
        login_required(views.VerAula.as_view()),
        name='ver_aula'
    ),
    path(
        'editar/aula/<int:id_aula>/',
        login_required(views.EditarAula.as_view()),
        name='editar_aula'
    ),
    path(
        'criar/artigo/<int:id_aula>/',
        login_required(views.CriarArtigo.as_view()),
        name='criar_artigo'
    ),
    path(
        'editar/artigo/<int:id_artigo>/',
        login_required(views.EditarArtigo.as_view()),
        name='editar_artigo'
    ),
    path(
        'ver/artigo/<int:id_artigo>/',
        login_required(views.VerArtigo.as_view()),
        name='ver_artigo'
    ),
    path(
        'criar/lista-exercicios/disciplina/<int:id_disciplina>/',
        login_required(views.CriarListaExercicios.as_view()),
        name='criar_lista_exercicios'
    ),
    path(
        'criar/relatorio/disciplina/<int:id_disciplina>/',
        login_required(views.CriarRelatorio.as_view()),
        name='criar_relatorio'
    ),
    path(
        'editar/relatorio/<int:id_relatorio>/',
        login_required(views.EditarRelatorio.as_view()),
        name='editar_relatorio'
    ),
    path(
        'responder/relatorio/<int:id_relatorio>/',
        login_required(views.ResponderRelatorio.as_view()),
        name='responder_relatorio'
    ),
    path(
        'criar/experimento/relatorio/<int:id_relatorio>/',
        login_required(views.AdicionarExperimentoRemotoNoRelatorio.as_view()),
        name='adicionar_experimento_remoto_no_relatorio'
    ),
    path(
        'remover/experimento/relatorio/<int:id_experimento>/',
        login_required(views.RemoverExperimentoNoLabRemoto.as_view()),
        name='remover_experimento_remoto_no_relatorio'
    ),
    path(
        'ver/experimento/<int:id_experimento>/',
        login_required(views.VerExperimento.as_view()),
        name='ver_experimento'
    ),
    path(
        'criar/execucao/<int:id_experimento>/',
        login_required(views.CriarExecucao.as_view()),
        name='criar_execucao'
    ),
    path(
        'duplicar/execucao/<int:id_experimento>/<int:id_execucao>/',
        login_required(views.DuplicarExecucao.as_view()),
        name='duplicar_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.VerExecucao.as_view()),
        name='ver_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/codigo/',
        login_required(views.VerCodigoExecucao.as_view()),
        name='ver_codigo_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/grafico/',
        login_required(views.VerGrafico.as_view()),
        name='ver_grafico'
    ),
    path(
        'criar/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.EditarExecucao.as_view()),
        name='editar_execucao'
    ),
    path(
        'executar/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.ExecutarExperimento.as_view()),
        name='executar_experimento'
    ),
    path(
        'configurar/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarConfiguracoesAvaliacao.as_view()),
        name='editar_configuracoes_avaliacao'
    ),
    path(
        'editar/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarQuestaoAvaliacao.as_view()),
        name='editar_questao_avaliacao'
    ),
    path(
        'editar/questao/<int:id_questao_avaliacao>/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarQuestaoAvaliacao.as_view()),
        name='editar_questao_avaliacao'
    ),
    path(
        'editar/avaliacao/<int:id_avaliacao>/criar-nova-questao/',
        login_required(views.AdicionarQuestaoNaAvaliacao.as_view()),
        name='adicionar_questao_avaliacao'
    ),
    path(
        'editar/remover-questao/<int:id_questao_avaliacao>/',
        login_required(views.RemoverQuestaoAvaliacao.as_view()),
        name='remover_questao_avaliacao'
    ),
    path(
        'editar/questao/<int:id_questao_avaliacao>/criar-nova-alternativa/',
        login_required(views.AdicionarAlternativaNaQuestaoDaLista.as_view()),
        name='adicionar_alternativa_questao_avaliacao'
    ),
    path(
        'responder/lista-exercicios/<int:id_avaliacao>/',
        login_required(views.ResponderQuestaoListaExercicios.as_view()),
        name='responder_questao_da_avaliacao'
    ),
    path(
        'responder/questao/<int:id_questao_avaliacao>/lista-exercicios/<int:id_avaliacao>/',
        login_required(views.ResponderQuestaoListaExercicios.as_view()),
        name='responder_questao_da_avaliacao'
    ),
    path(
        'adicionar/anexo/<str:onde>/<int:id>/',
        login_required(views.AdicionarAnexo.as_view()),
        name='adicionar_anexo_onde'
    ),
    path(
        'remover/anexo/<str:onde>/<int:id_anexo>/',
        login_required(views.RemoverAnexoOnde.as_view()),
        name='remover_anexo_onde'
    ),
    path(
        'ver/correcao/lista-exercicios/<int:id_lista>/',
        login_required(views.VerCorrecaoAvaliacao.as_view()),
        name='ver_correcao_lista_exercicios'
    ),
    path(
        'ver/entregas/avaliacao/<int:id_avaliacao>/',
        login_required(views.VerEntregasAvaliacao.as_view()),
        name='ver_entregas_avaliacao'
    ),
    path(
        'corrigir/avaliacao/<int:id_avaliacao>/aluno/<int:id_aluno>/',
        login_required(views.CorrigirQuestaoAvaliacao.as_view()),
        name='corrigir_avaliacao_aluno'
    ),
]

src/sistema_gerenciamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('almoxarifado/', include('almoxarifado.urls')),
    path('educacao/', include('educacao.urls')),
    path('lab_remoto/', include('lab_remoto.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
    ]

src/almoxarifado/models.py
from django.db import models
from django.utils.deconstruct import deconstructible
from django.conf.global_settings import MEDIA_ROOT
from ckeditor_uploader.fields import RichTextUploadingField

from usuarios.models import Usuario, Area

import os
from uuid import uuid4


@deconstructible
class UploadToPathAndRename(object):

    def __init__(self, path):
        self.sub_path = path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # get filename
        if instance.pk:
            filename = '{}.{}'.format(instance.pk, ext)
        else:
            # set filename as random string
            filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.sub_path, filename)


class Sala(models.Model):
    nome = models.CharField(max_length=200)
    sigla = models.CharField(max_length=20)
    area = models.ForeignKey(
        Area,
        on_delete=models.PROTECT,
        related_name='sala_area'
    )
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.sigla

    class Meta:
        verbose_name_plural = "Salas"
        ordering = ["sigla", ]


class Categoria(models.Model):
    nome = models.CharField(max_length=200)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.nome

    class Meta:
        verbose_name_plural = "Categorias"
        ordering = ["nome", ]


class Fabricante(models.Model):
    nome = models.CharField(max_length=200)
    site = models.URLField()
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % self.nome

    class Meta:
        verbose_name_plural = 'Fabricantes'
        ordering = ['data_criacao', ]


class Modelo(models.Model):
    fabricante = models.ForeignKey(
        Fabricante,
        on_delete=models.PROTECT,
        related_name='modelo_fabricante',
        blank=True,
        null=True
    )
    nome = models.CharField(max_length=200)
    foto = models.ImageField(upload_to=UploadToPathAndRename(os.path.join(MEDIA_ROOT, 'upload', 'modelo')))
    site = models.URLField()
    data_criacao = models.DateTimeField(auto_now_add=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)

    def __str__(self):
        return '%s' % self.nome

    class Meta:
        verbose_name_plural = "Modelos"
        ordering = ["nome", ]


class Item(models.Model):
    TIPO_EQUIPAMENTO = 'E'
    TIPO_MATERIAL_CONSUMO = 'MC'
    TIPOS_ITENS = (
        (TIPO_EQUIPAMENTO, 'Equipamento'),
        (TIPO_MATERIAL_CONSUMO, 'Material de consumo'),
    )
    tipo = models.CharField(
        max_length=2,
        choices=TIPOS_ITENS,
        default=TIPO_MATERIAL_CONSUMO
    )

    # nome = models.CharField(max_length=1000)
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    modelo = models.ForeignKey(Modelo, on_delete=models.PROTECT)
    patrimonio = models.CharField(max_length=100, default='', blank=True)
    foto = models.ImageField(upload_to=UploadToPathAndRename(os.path.join(MEDIA_ROOT, 'upload', 'almoxarifado_item')))

    UNIDADE_KG = 'KG'
    UNIDADE_ROLO = 'R'
    UNIDADE_METRO = 'M'
    UNIDADE_UNIDADE = 'U'
    UNIDADE_ = ''
    OPCOES_UNIDADES = (
        (UNIDADE_KG, 'KG'),
        (UNIDADE_ROLO, 'Rolo'),
        (UNIDADE_METRO, 'Metro'),
        (UNIDADE_UNIDADE, 'Unidade'),
    )
    unidade_medida = models.CharField(
        max_length=2,
        choices=TIPOS_ITENS,
        default=TIPO_MATERIAL_CONSUMO
    )
    quantidade = models.DecimalField(max_digits=8, decimal_places=2, blank=True, default=0)

    # Sobre a aquisição do item
    preco_aquisicao = models.DecimalField(max_digits=8, decimal_places=2, blank=True)

    # Sobre a localização do item
    localizacao_padrao = models.ForeignKey(
        Sala,
        on_delete=models.PROTECT,
        related_name='equipamento_localizacaopadrao',
        blank=True
    )
    localizacao_atual = models.ForeignKey(
        Sala,
        on_delete=models.PROTECT,
        related_name='equipamento_localizacaoatual',
        blank=True
    )

    def __str__(self):
        return '%s: %s' % (self.categoria.nome, self.modelo.nome)

    class Meta:
        verbose_name_plural = "Equipamentos"
        ordering = ['categoria', 'modelo', ]


class OcorrenciaItem(models.Model):
    item = models.ForeignKey(
        Item,
        on_delete=models.PROTECT
    )
    texto = RichTextUploadingField()
    data_criacao = models.DateTimeField(auto_now_add=True)


class SolicitacaoEmprestimo(models.Model):
    # Sobre quem solicita o material
    requerente = models.ForeignKey(Usuario, on_delete=models.PROTECT)
    justificativa = models.CharField(max_length=2000, blank=False)

    # Sobre a entrega do material
    horario_entrega = models.DateTimeField(auto_now_add=True)
    sala_entrega = models.ForeignKey(Sala, on_delete=models.PROTECT)

    # Quem vai separar o material?
    tecnico = models.ForeignKey(
        Usuario,
        on_delete=models.PROTECT,
        related_name='solicitacaoemprestimo_tecnico',
        blank=True,
        null=True
    )

    # Sobre o status do empréstimo
    STATUS_REGISTRADO = '1'
    STATUS_EM_SEPARACAO = '2'  # um ténico foi atribuído para separar o material solicitado
    STATUS_DISPONIVEL = '3'
    STATUS_RETIRADO = '4'
    STATUS_PENDENTE = '5'
    STATUS_FINALIZADO = '6'
    OPCOES_STATUS = (
        (STATUS_REGISTRADO, 'Registrado'),
        (STATUS_EM_SEPARACAO, 'Em separação'),
        (STATUS_DISPONIVEL, 'Disponível'),
        (STATUS_RETIRADO, 'Retirado'),
        (STATUS_PENDENTE, 'Pendente'),
        (STATUS_FINALIZADO, 'Finalizado')
    )
    status = models.CharField(
        choices=OPCOES_STATUS,
        max_length=2,
        blank=False,
        default=STATUS_REGISTRADO
    )

    data_registro = models.DateTimeField(auto_now_add=True)
    data_em_seperacao = models.DateTimeField(auto_now_add=True)
    data_disponivel = models.DateTimeField(auto_now_add=True)
    data_retirado = models.DateTimeField(auto_now_add=True)
    data_devolucao = models.DateTimeField(auto_now_add=True)


class ItemSolicitado(models.Model):
    # Sobre a solicitação
    solicitacao = models.ForeignKey(SolicitacaoEmprestimo, on_delete=models.PROTECT)
    item = models.ForeignKey(Item, on_delete=models.PROTECT)

    # O requerente preenche
    quantidade_solicitada = models.PositiveIntegerField(default=1)

    # O técnico preenche
    quantidade_aprovada = models.PositiveIntegerField(default=1)
    justificativa = models.CharField(max_length=1000, blank=True)

    # Avaliação
    pronto_no_horario_requerente = models.BooleanField(default=True)
    problema_reportado_requerente = models.BooleanField(default=False)
    descricao_problema_requerente = models.CharField(max_length=100)
    devolvido = models.BooleanField(default=False)                      # técnico
    item_voltou_com_defeito = models.BooleanField(default=False)        # técnico
    quantidade_retornada = models.IntegerField(default=0)               # técnico

src/almoxarifado/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

from .models import *


class FormNovoFabricante(forms.ModelForm):
    class Meta:
        model = Fabricante
        fields = ('nome', 'site', )


class FormEditarFabricante(forms.ModelForm):
    class Meta:
        model = Fabricante
        fields = ('nome', 'site', )


class FormNovoModelo(forms.ModelForm):
    class Meta:
        model = Modelo
        fields = ('categoria', 'fabricante', 'nome', 'site', 'foto', )


class FormEditarModelo(forms.ModelForm):
    class Meta:
        model = Modelo
        fields = ('categoria', 'fabricante', 'nome', 'site', 'foto', )


class FormCriarTipoMaterial(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ('nome', )

src/almoxarifado/templates/almoxarifado/editar_modelo.html
{% extends "almoxarifado/index.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}





{% block bibliotecas %}
    <link rel="stylesheet" type="text/css" href="{% static 'choosen/chosen_v1.8.7/chosen.min.css' %}">
    <script type="text/javascript" charset="utf8" src="{% static 'choosen/chosen_v1.8.7/chosen.jquery.min.js' %}"></script>
{% endblock %}


{% block barra_horizontal %}
{% endblock %}


{% block corpo_pagina %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card cartao">
                <h5 class="card-header cartao-titulo">
                    <img src="{% static 'icones/modelo.svg' %}">
                    Editar modelo {{ modelo.nome }}
                </h5>
                <div class="card-body">
                    <form method="post" class="formulario sem-asterisco">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <input type="submit" role="button" class="btn btn-primary" value="Salvar">
{#                        <a href="{% url 'almoxarifado:ver_fabricantes' %}" class="btn btn-danger">Remover</a>#}
                        <a href="{% url 'almoxarifado:ver_modelos' %}" class="btn btn-warning">Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}




{% block javascript %}
     $("#id_fabricante").chosen();
     $("#id_categoria").chosen();
{% endblock %}

src/almoxarifado/templates/almoxarifado/index_equipamentos.html
{% extends "almoxarifado/index.html" %}
{% load staticfiles %}

{% block barra_horizontal %}
    {#    <li>#}
    {#        <a class="btn btn-secondary botao-barra-horizontal" href="#">#}
    {#            <span><img src="{% static 'icones/novo.svg'%}" width="20px"></span>Criar#}
    {#        </a>#}
    {#    </li>#}
    {##}
    {#    <li>#}
    {#        <a class="btn btn-secondary botao-barra-horizontal" href="#">#}
    {#            <span><img src="{% static 'icones/apagar.svg'%}" width="20px"></span>Remover#}
    {#        </a>#}
    {#    </li>#}
{% endblock %}


{% block barra_avisos_verde %}
    {% if fabricante_criado_com_sucesso %}
        <p>O fabricante {{ novo_fabricante }} foi criado com sucesso!</p>
    {% endif %}
    {% if modelo_criado_com_sucesso %}
        <p>O modelo {{ novo_modelo }} ({{ novo_modelo.fabricante.nome }}) foi criado com sucesso!</p>
    {% endif %}
{% endblock %}


{% block corpo_pagina %}
    <div class="row">
        <div class="col-lg-12">

            <div class="card cartao">
                <h5 class="card-header cartao-titulo"><img src="{% static 'icones/categoria.svg' %}">
                    Tipos de materiais
                </h5>
                <div class="card-body">
                    {% if equipamentos.count == 0 %}
                        <p class="card-text">
                            Não há nenhum tipo de material cadastrado.
                            Use os botões abaixo para cadastrar um tipo de material.
                        </p>
                    {% elif equipamentos.count == 1 %}
                        <p class="card-text">
                            Existe 1 tipo de material cadastrado
                        </p>
                    {% else %}
                        <p class="card-text">
                            Existem {{ equipamentos.count }} tipos de materiais cadastrados
                        </p>
                    {% endif %}

                    {% if equipamentos.count > 0 %}
                        {% with fabricante=equipamentos.last %}
                            <p class="card-text">
                                Último tipo de material cadastrado: <b>{{ equipamentos.nome }}</b>
                            </p>
                        {% endwith %}
                    {% endif %}

                    <p class="card-title">
                        <a href="{% url 'almoxarifado:criar_tipo_item' %}"
                           class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/novo.svg' %}" width="20px">Criar
                        </a>
                        <a href="{% url 'almoxarifado:ver_fabricantes' %}"
                           class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/lupa.svg' %}" width="20px">Ver
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">

            <div class="card cartao">
                <h5 class="card-header cartao-titulo"><span><img src="{% static 'icones/fabricante.svg' %}"></span>Fabricantes
                </h5>
                <div class="card-body">
                    {% if fabricantes.count == 0 %}
                        <p class="card-text">Não há nenhum fabricante cadastrado. Use os botões abaixo para cadastrar um
                            fabricante.</p>
                    {% elif fabricantes.count == 1 %}
                        <p class="card-text">Existe 1 fabricante cadastrado</p>
                    {% else %}
                        <p class="card-text">Existem {{ fabricantes.count }} fabricantes de equipamentos cadastrados</p>
                    {% endif %}

                    {% if fabricantes.count > 0 %}
                        {% with fabricante=fabricantes.last %}
                            <p class="card-text">Último fabricante cadastrado: <b>{{ fabricante.nome }}</b></p>
                        {% endwith %}
                    {% endif %}

                    <p class="card-title">
                        <a href="{% url 'almoxarifado:criar_fabricante' %}"
                           class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/novo.svg' %}" width="20px">Criar
                        </a>
                        <a href="{% url 'almoxarifado:ver_fabricantes' %}"
                           class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/lupa.svg' %}" width="20px">Ver
                        </a>
                    </p>
                </div>
            </div>

            <div class="card cartao">
                <h5 class="card-header cartao-titulo"><span><img src="{% static 'icones/equipamento.svg' %}"></span>Equipamentos
                </h5>
                <div class="card-body">
                    {% if equipamentos.count == 0 %}
                        <p class="card-text">Não há nenhum equipamento cadastrado. Use os botões abaixo para cadastrar
                            um equipamento.</p>
                    {% elif equipamentos.count == 1 %}
                        <p class="card-text">Existe 1 equipamento cadastrado</p>
                    {% else %}
                        <p class="card-text">Existem {{ equipamentos.count }} equipamentos cadastrados</p>
                    {% endif %}

                    {% if equipamentos.count > 0 %}
                        {% with fabricante=equipamentos.last %}
                            <p class="card-text">Último fabricante cadastrado: <b>{{ equipamentos.nome }}</b></p>
                        {% endwith %}
                    {% endif %}

                    <p class="card-title">
                        <a href="{% url 'almoxarifado:criar_fabricante' %}"
                           class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/novo.svg' %}" width="20px">Criar
                        </a>
                        <a href="{% url 'almoxarifado:ver_fabricantes' %}"
                           class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/lupa.svg' %}" width="20px">Ver
                        </a>
                    </p>
                </div>
            </div>

        </div>

        <div class="col-lg-6">

            <div class="card cartao">
                <h5 class="card-header cartao-titulo">
                    <img src="{% static 'icones/modelo.svg' %}">
                    Modelos de equipamentos
                </h5>
                <div class="card-body">
                    {% if modelos.count == 0 %}
                        <p class="card-text">
                            Não há nenhum modelo de equipamento cadastrado.
                            Use os botões abaixo para cadastrar um modelo de equipamento.
                        </p>
                    {% elif modelos.count == 1 %}
                        <p class="card-text">
                            Existe 1 modelo de equipamento cadastrado
                        </p>
                    {% else %}
                        <p class="card-text">
                            Existem {{ modelos.count }} modelos de equipamentos cadastrados
                        </p>
                    {% endif %}

                    {% if modelos.count > 0 %}
                        {% with modelo=modelos.last %}
                            <p class="card-text">Último modelo cadastrado: <b>{{ modelo.nome }}</b></p>
                        {% endwith %}
                    {% endif %}

                    <p class="card-title">
                        <a href="{% url 'almoxarifado:criar_modelo' %}" class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/novo.svg' %}" width="20px">Criar
                        </a>
                        <a href="{% url 'almoxarifado:ver_modelos' %}" class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/lupa.svg' %}" width="20px">Ver
                        </a>
                    </p>
                </div>
            </div>

            <div class="card cartao">
                <h5 class="card-header cartao-titulo"><img src="{% static 'icones/parafuso.svg' %}">
                    Material de consumo
                </h5>
                <div class="card-body">
                    {% if equipamentos.count == 0 %}
                        <p class="card-text">
                            Não há nenhum material cadastrado. Use os botões abaixo para cadastrar um material.
                        </p>
                    {% elif equipamentos.count == 1 %}
                        <p class="card-text">Existe 1 material cadastrado</p>
                    {% else %}
                        <p class="card-text">Existem {{ equipamentos.count }} materiais cadastrados</p>
                    {% endif %}

                    {% if equipamentos.count > 0 %}
                        {% with fabricante=equipamentos.last %}
                            <p class="card-text">Último fabricante cadastrado: <b>{{ equipamentos.nome }}</b></p>
                        {% endwith %}
                    {% endif %}

                    <p class="card-title">
                        <a href="{% url 'almoxarifado:criar_fabricante' %}"
                           class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/novo.svg' %}" width="20px">Criar
                        </a>
                        <a href="{% url 'almoxarifado:ver_fabricantes' %}"
                           class="btn btn-outline-secondary botao-cartao">
                            <img src="{% static 'icones/lupa.svg' %}" width="20px">Ver
                        </a>
                    </p>
                </div>
            </div>

        </div>
    </div>
{% endblock %}




{% block javascript %}
{% endblock %}