src/almoxarifado/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'almoxarifado'

urlpatterns = [
    path(
        '',
        views.Index.as_view(),
        name='index'
    ),
    path(
        'equipamentos/',
        views.IndexEquipamentos.as_view(),
        name='index_equipamentos'
    ),
    path(
        'equipamentos/criado/fabricante/<int:id_fabricante>/',
        views.IndexEquipamentos.as_view(),
        name='index_equipamentos'
    ),
    path(
        'equipamentos/criado/modelo/<int:id_modelo>/',
        views.IndexEquipamentos.as_view(),
        name='index_equipamentos'
    ),
    path(
        'equipamentos/criar/fabricante',
        views.CriarFabricante.as_view(),
        name='criar_fabricante'
    ),
    path(
        'equipamentos/ver/fabricantes',
        views.VerFabricantes.as_view(),
        name='ver_fabricantes'
    ),
    path(
        'equipamentos/editar/fabricante/<int:id_fabricante>',
        views.EditarFabricante.as_view(),
        name='editar_fabricante'
    ),
    path(
        'equipamentos/criar/modelo',
        views.CriarModelo.as_view(),
        name='criar_modelo'
    ),
    path(
        'equipamentos/ver/modelos',
        views.VerModelos.as_view(),
        name='ver_modelos'
    ),
    path(
        'equipamentos/editar/modelo/<int:id_modelo>',
        views.EditarModelo.as_view(),
        name='editar_modelo'
    ),
    path(
        'criar/tipo-de-item/',
        views.CriarTipoItem.as_view(),
        name='criar_tipo_item'
    ),
]

src/educacao/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'educacao'

urlpatterns = [
    path(
        '',
        login_required(views.Index.as_view()),
        name='index'
    ),
    path(
        '<int:id_disciplina>',
        login_required(views.Index.as_view()),
        name='index'
    ),
    path(
        'criar/disciplina/',
        login_required(views.CriarDisciplina.as_view()),
        name='criar_disciplina'
    ),
    path(
        'inscrever/disciplina/<int:id_disciplina>/',
        login_required(views.InscreverNaDisciplina.as_view()),
        name='matricular_na_disciplina'
    ),
    path(
        'editar/disciplina/<int:id_disciplina>/',
        (views.EditarDisciplina.as_view()),
        name='editar_disciplina'
    ),
    path(
        'ver/disciplina/<int:id_disciplina>/',
        login_required(views.VerDisciplina.as_view()),
        name='ver_disciplina'
    ),
    path(
        'ver/aula/<int:id_aula>/',
        login_required(views.VerAula.as_view()),
        name='ver_aula'
    ),
    path(
        'editar/aula/<int:id_aula>/',
        login_required(views.EditarAula.as_view()),
        name='editar_aula'
    ),
    path(
        'criar/artigo/<int:id_aula>/',
        login_required(views.CriarArtigo.as_view()),
        name='criar_artigo'
    ),
    path(
        'editar/artigo/<int:id_artigo>/',
        login_required(views.EditarArtigo.as_view()),
        name='editar_artigo'
    ),
    path(
        'ver/artigo/<int:id_artigo>/',
        login_required(views.VerArtigo.as_view()),
        name='ver_artigo'
    ),
    path(
        'criar/lista-exercicios/disciplina/<int:id_disciplina>/',
        login_required(views.CriarListaExercicios.as_view()),
        name='criar_lista_exercicios'
    ),
    path(
        'criar/relatorio/disciplina/<int:id_disciplina>/',
        login_required(views.CriarRelatorio.as_view()),
        name='criar_relatorio'
    ),
    path(
        'editar/relatorio/<int:id_relatorio>/',
        login_required(views.EditarRelatorio.as_view()),
        name='editar_relatorio'
    ),
    path(
        'responder/relatorio/<int:id_relatorio>/',
        login_required(views.ResponderRelatorio.as_view()),
        name='responder_relatorio'
    ),
    path(
        'criar/experimento/relatorio/<int:id_relatorio>/',
        login_required(views.AdicionarExperimentoRemotoNoRelatorio.as_view()),
        name='adicionar_experimento_remoto_no_relatorio'
    ),
    path(
        'remover/experimento/relatorio/<int:id_experimento>/',
        login_required(views.RemoverExperimentoNoLabRemoto.as_view()),
        name='remover_experimento_remoto_no_relatorio'
    ),
    path(
        'ver/experimento/<int:id_experimento>/',
        login_required(views.VerExperimento.as_view()),
        name='ver_experimento'
    ),
    path(
        'criar/execucao/<int:id_experimento>/',
        login_required(views.CriarExecucao.as_view()),
        name='criar_execucao'
    ),
    path(
        'duplicar/execucao/<int:id_experimento>/<int:id_execucao>/',
        login_required(views.DuplicarExecucao.as_view()),
        name='duplicar_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.VerExecucao.as_view()),
        name='ver_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/codigo/',
        login_required(views.VerCodigoExecucao.as_view()),
        name='ver_codigo_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/grafico/',
        login_required(views.VerGrafico.as_view()),
        name='ver_grafico'
    ),
    path(
        'criar/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.EditarExecucao.as_view()),
        name='editar_execucao'
    ),
    path(
        'executar/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.ExecutarExperimento.as_view()),
        name='executar_experimento'
    ),
    path(
        'configurar/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarConfiguracoesAvaliacao.as_view()),
        name='editar_configuracoes_avaliacao'
    ),
    path(
        'editar/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarQuestaoAvaliacao.as_view()),
        name='editar_questao_avaliacao'
    ),
    path(
        'editar/questao/<int:id_questao_avaliacao>/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarQuestaoAvaliacao.as_view()),
        name='editar_questao_avaliacao'
    ),
    path(
        'editar/avaliacao/<int:id_avaliacao>/criar-nova-questao/',
        login_required(views.AdicionarQuestaoNaAvaliacao.as_view()),
        name='adicionar_questao_avaliacao'
    ),
    path(
        'editar/remover-questao/<int:id_questao_avaliacao>/',
        login_required(views.RemoverQuestaoAvaliacao.as_view()),
        name='remover_questao_avaliacao'
    ),
    path(
        'editar/questao/<int:id_questao_avaliacao>/criar-nova-alternativa/',
        login_required(views.AdicionarAlternativaNaQuestaoDaLista.as_view()),
        name='adicionar_alternativa_questao_avaliacao'
    ),
    path(
        'responder/lista-exercicios/<int:id_avaliacao>/',
        login_required(views.ResponderQuestaoListaExercicios.as_view()),
        name='responder_questao_da_avaliacao'
    ),
    path(
        'responder/questao/<int:id_questao_avaliacao>/lista-exercicios/<int:id_avaliacao>/',
        login_required(views.ResponderQuestaoListaExercicios.as_view()),
        name='responder_questao_da_avaliacao'
    ),
    path(
        'adicionar/anexo/<str:onde>/<int:id>/',
        login_required(views.AdicionarAnexo.as_view()),
        name='adicionar_anexo_onde'
    ),
    path(
        'remover/anexo/<str:onde>/<int:id_anexo>/',
        login_required(views.RemoverAnexoOnde.as_view()),
        name='remover_anexo_onde'
    ),
    path(
        'ver/correcao/lista-exercicios/<int:id_lista>/',
        login_required(views.VerCorrecaoAvaliacao.as_view()),
        name='ver_correcao_lista_exercicios'
    ),
    path(
        'ver/entregas/avaliacao/<int:id_avaliacao>/',
        login_required(views.VerEntregasAvaliacao.as_view()),
        name='ver_entregas_avaliacao'
    ),
    path(
        'corrigir/avaliacao/<int:id_avaliacao>/aluno/<int:id_aluno>/',
        login_required(views.CorrigirQuestaoAvaliacao.as_view()),
        name='corrigir_avaliacao_aluno'
    ),
]

src/lab_remoto/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'lab_remoto'

urlpatterns = [
    path(
        '',
        login_required(views.Index.as_view()),
        name='index'
    ),

    path(
        'criar/kit/',
        login_required(views.CriarKit.as_view()),
        name='criar_kit'
    ),

    path(
        'editar/kit/<int:id_kit>/',
        login_required(views.EditarKit.as_view()),
        name='editar_kit'
    ),

    path(
        'remover/kit/<int:id_kit>/',
        login_required(views.RemoverKit.as_view()),
        name='remover_kit'
    ),

    path(
        'criar/ensaio/',
        login_required(views.CriarEnsaio.as_view()),
        name='criar_ensaio'
    ),

    path(
        'remover/ensaio/<int:id_ensaio>/',
        login_required(views.RemoverEnsaio.as_view()),
        name='remover_ensaio'
    ),

    path(
        'editar/ensaio/<int:id_ensaio>/',
        login_required(views.EditarEnsaio.as_view()),
        name='editar_ensaio'
    ),

    path(
        'remover/parametro/<int:id_parametro>/',
        login_required(views.RemoverParametro.as_view()),
        name='remover_parametro'
    ),

    path(
        'editar/executar/ensaio/<int:id_ensaio>/',
        login_required(views.ExecutarEnsaio.as_view()),
        name='executar_ensaio'
    ),
]

src/sistema_gerenciamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('almoxarifado/', include('almoxarifado.urls')),
    path('educacao/', include('educacao.urls')),
    path('lab_remoto/', include('lab_remoto.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
    ]

src/usuarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.pagina_entrar,
        name='pagina_entrar'
    ),
    path(
        'usuario_criado/',
        views.pagina_entrar_usuario_criado,
        name='pagina_entrar_usuario_criado'
    ),
    path(
        'criar_conta/',
        views.pagina_criar_conta,
        name='pagina_criar_conta'
    ),
    path(
        'entrar/',
        views.pagina_entrar,
        name='pagina_entrar'
    ),
    path(
        'sair/',
        views.pagina_sair,
        name='pagina_sair'
    ),
]

src/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Usuario


class FormularioEntrar(forms.Form):
    prontuario = forms.CharField(
        label='',
        max_length=200,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Prontuário',
                'class': 'form-control'
            }
        )
    )

    senha = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Senha',
                'class': 'form-control'
            }
        )
    )


class FormularioCriarConta(forms.Form):
    primeiro_nome = forms.CharField(
        label='Primeiro nome',
        max_length=200,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Primeiro nome',
                'class': 'form-control'
            }
        )
    )

    sobrenome = forms.CharField(
        label='Sobrenome',
        max_length=200,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Sobrenome',
                'class': 'form-control'
            }
        )
    )

    prontuario = forms.CharField(
        label='Prontuário',
        max_length=20,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Exemplo: SJ0123456789',
                'class': 'form-control'
            }
        )
    )

    email = forms.CharField(
        label='E-mail',
        max_length=200,
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'E-mail',
                'class': 'form-control'
            }
        )
    )

    senha = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Senha',
                'class': 'form-control'}
        )
    )
    

src/usuarios/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views import View

import datetime

from . import forms
from .models import Usuario


class SentinelaViewBasica(View):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.texto_aviso_verde = None
        self.texto_aviso_vermelho = None
        self.contexto = dict()

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)

        self.usuario = self.selecionar_usuario(request)
        # self.instituicao = None
        self.contexto['usuario'] = self.usuario

    def selecionar_usuario(self, request):
        usuario = None, None

        usuario_django = request.user
        query_usuario = Usuario.objects.filter(usuario_django=usuario_django)
        if query_usuario.count() == 1:
            usuario = query_usuario[0]

        return usuario


def pagina_entrar_usuario_criado(request):
    return pagina_entrar(request, usuario_criado=True)


def pagina_entrar(request, usuario_criado=None):
    form = forms.FormularioEntrar()
    texto_aviso_vermelho = None
    if usuario_criado is None:
        texto_aviso_verde = ''
    else:
        texto_aviso_verde = 'Usuário criado com sucesso.'

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('educacao:index'))

    else:
        if request.method == 'POST':
            form = forms.FormularioEntrar(request.POST)
            if form.is_valid():
                prontuario = form.cleaned_data['prontuario'].lower()
                senha = form.cleaned_data['senha']

                usuario_django = authenticate(username=prontuario, password=senha)
                if usuario_django is not None:
                    # usuario = Usuario.objects.get(prontuario=prontuario)
                    if usuario_django.is_active:
                        login(request, usuario_django)

                        usuario = Usuario.objects.get(usuario_django=usuario_django)
                        usuario.data_ultimo_acesso = datetime.datetime.now()
                        usuario.save()

                        return HttpResponseRedirect(reverse('educacao:index'))
                    else:
                        texto_aviso_vermelho = 'Usuário inativo.'
                else:
                    texto_aviso_vermelho = 'Nome de usuário ou senha está incorreto.'

        contexto = {
            'formulario_entrar': form,
            'texto_aviso_vermelho': texto_aviso_vermelho,
            'texto_aviso_verde': texto_aviso_verde,
        }
        return render(request, 'usuarios/pagina_entrar.html', contexto)


def pagina_criar_conta(request):
    formulario = forms.FormularioCriarConta()
    texto_aviso_verde = None

    if request.method == 'POST':
        formulario = forms.FormularioCriarConta(request.POST)
        if formulario.is_valid():
            primeiro_nome = formulario.cleaned_data['primeiro_nome']
            sobrenome = formulario.cleaned_data['sobrenome']
            prontuario = formulario.cleaned_data['prontuario'].lower()
            email = formulario.cleaned_data['email']
            senha = formulario.cleaned_data['senha']

            usuario_django = User()
            usuario_django.username = prontuario
            usuario_django.first_name = primeiro_nome
            usuario_django.last_name = sobrenome
            usuario_django.email = email
            usuario_django.set_password(senha)
            usuario_django.is_active = True
            usuario_django.is_staff = False
            usuario_django.is_superuser = False
            usuario_django.save()

            novo_usuario = Usuario(
                prontuario=prontuario,
                usuario_django=usuario_django,
                tipo=Usuario.TIPO_ALUNO
            )
            novo_usuario.save()

            return redirect('pagina_entrar_usuario_criado')

    contexto = {
        'formulario': formulario,
        'texto_aviso_verde': texto_aviso_verde,
    }

    if texto_aviso_verde is None:
        return render(request, 'usuarios/pagina_criar_conta.html', contexto)


@login_required
def pagina_sair(request):
    logout(request)
    return redirect('pagina_entrar')

src/usuarios/templates/usuarios/base.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}
{% load crispy_forms_tags %}

{# Bootstrap 4.3.1 #}
<script src="{% static "bootstrap/popper.min.js" %}"></script>
<script src="{% static "bootstrap/jquery-3.4.1.min.js" %}"></script>
<link rel="stylesheet" href="{% static "bootstrap/bootstrap.min.css" %}">
<script src="{% static "bootstrap/bootstrap.min.js" %}"></script>
<link href="{% static "css/usuarios.css" %}" rel="stylesheet">

<head>
    <meta charset="utf-8">
    <title>Sistema Sentinela</title>
</head>

<body>

    <div class="container">

        {% if texto_aviso_verde %}
        <div class="alert alert-success alert-dismissible fade show" role="aviso">
            <strong>{{ texto_aviso_verde }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        {% if texto_aviso_vermelho %}
            <div class="alert alert-danger alert-dismissible fade show" role="aviso">
                <strong>{{ texto_aviso_vermelho }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}

    {% block formulario %}
    {% endblock %}

    </div>
</body>


{% block javascript %}
{% endblock %}



</html>

src/usuarios/templates/usuarios/index.html
<!DOCTYPE html>
<html lang="pt">

{# Usei essa página como base #}
{# https://bootstrapious.com/p/bootstrap-vertical-navbar #}

{% load staticfiles %}

{# Bootstrap 4.3.1 #}
<script src="{% static "bootstrap/popper.min.js" %}"></script>
<script src="{% static "bootstrap/jquery-3.4.1.min.js" %}"></script>
<link rel="stylesheet" href="{% static "bootstrap/bootstrap.min.css" %}">
<script src="{% static "bootstrap/bootstrap.min.js" %}"></script>

{# CSS geral #}
<link rel="stylesheet" type="text/css" href="{% static 'css/sentinela.css' %}">
{# CSS específico do módulo de almoxarifado #}
<link rel="stylesheet" type="text/css" href="{% static 'css/almoxarifado.css' %}">

{% block bibliotecas %}
{% endblock %}

<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{% static 'icones/sentinela_logo.svg' %}" />
    <title>Sentinela</title>
</head>

<body>


<nav class="navbar sticky-top navbar-expand-sm navbar-dark bg-dark">

    <a class="navbar-brand horizontal-nav" href="#">
        <img src="{% static 'icones/sentinela_logo.svg' %}" width="40px" class="mr-3 img-thumbnail shadow-sm">
        Sentinela
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% block barra_horizontal %}
            {% endblock %}
        </ul>



    <div class="navbar-text btn-group">
        <button type="button" class="btn btn-outline-light dropdown-toggle" data-toggle="dropdown">
            {% if usuario.tipo == usuario.TIPO_ALUNO %}
                <img src="{% static 'icones/aluno.svg' %}" width="30px" class="mr-3 rounded-circle img-thumbnail">
            {% elif usuario.tipo == usuario.TIPO_DOCENTE %}
                <img src="{% static 'icones/docente.svg' %}" width="30px" class="mr-3 rounded-circle img-thumbnail">
            {% elif usuario.tipo == usuario.TIPO_TECNICO_LABORATORIO %}
                <img src="{% static 'icones/cientista_homem.svg' %}" width="30px" class="mr-3 rounded-circle img-thumbnail">
            {% elif usuario.tipo == usuario.TIPO_TECNICO_ADMINISTRATIVO %}
                <img src="{% static 'icones/tecnico.svg' %}" width="30px" class="mr-3 rounded-circle img-thumbnail">
            {% else %}
                <img src="{% static 'icones/usuario.svg' %}" width="30px" class="mr-3 rounded-circle img-thumbnail">
            {% endif %}
        </button>

        <div class="dropdown-menu dropdown-menu-right">
            <p class="dropdown-header">{{ usuario.usuario_django.first_name }}</p>
        <div class="dropdown-divider"></div>
{#            <a class="dropdown-item text-dark" href="#">#}
{#                Minha conta#}
{#            </a>#}
            <a class="dropdown-item text-dark" href="#">
                Mudar minha senha
            </a>
            <a class="dropdown-item text-dark" href="{% url 'pagina_sair' %}">
                Sair
            </a>
        </div>
    </div>

    </div>
</nav>

{# Sidebar #}
<div class="vertical-nav bg-light" id="sidebar">

    <p class="text-light font-weight-bold text-uppercase px-3 py-3 small pb-4 mb-0 bg-secondary">Módulos</p>

    <ul class="nav flex-column bg-light mb-0">
{#        {% block sidebar_almoxarifado %}#}
{#        <li class="nav-item">#}
{#            <a href="{% url 'almoxarifado:index' %}" class="nav-link text-dark">#}
{#                <img src="{% static 'icones/almoxarifado.svg' %}" alt="" class="mr-1 img-thumbnail" width="40px">#}
{#                Almoxarifado#}
{#            </a>#}
{#        </li>#}
{#        {% endblock %}#}

{#        <li class="nav-item">#}
{#            <a href="#" class="nav-link text-dark">#}
{#                <img src="{% static 'icones/compras.png' %}" alt="" class="mr-1 img-thumbnail" width="40px"> Compras#}
{#            </a>#}
{#        </li>#}

        <li class="nav-item">
            {% block sidebar_educacao %}
            <a href="{% url 'educacao:index' %}" class="nav-link text-dark">
                <img src="{% static 'icones/livro.svg' %}" alt="" class="mr-1 img-thumbnail" width="40px">
                Educação
            </a>
            {% endblock %}
        </li>

{#        <li class="nav-item">#}
{#            <a href="#" class="nav-link text-dark">#}
{#                <img src="{% static 'icones/horario.svg' %}" alt="" class="mr-1 img-thumbnail" width="40px"> Horário docente#}
{#            </a>#}
{#        </li>#}


        {# Menu Instituição #}
{#        <li class="nav-item">#}
{#            <a href="#" class="nav-link text-dark">#}
{#                <img src="{% static 'icones/instituicao.svg' %}" alt="" class="mr-1 img-thumbnail" width="40px"> Instituição#}
{#            </a>#}
{##}
{#            <ul class="nav flex-column sidebar-subitens sidebar-subitens-instituicao">#}
{#                <li class="nav-item sidebar-subitem">#}
{#                    <a href="#">#}
{#                        <table>#}
{#                            <tr>#}
{#                                <td><img src="{% static 'icones/sala.svg' %}" class="img-thumbnail"></td>#}
{#                                <td>Salas</td>#}
{#                            </tr>#}
{#                        </table>#}
{#                    </a>#}
{#                </li>#}
{#            </ul>#}
{#        </li>#}

        {% block sidebar_lab_remoto %}
        {% if usuario.tipo == usuario.TIPO_DOCENTE %}
        <li class="nav-item">
            <a href="{% url 'lab_remoto:index' %}" class="nav-link text-dark">
                <img src="{% static 'icones/lab_remoto.svg' %}" alt="" class="mr-1 img-thumbnail" width="40px">
                Lab. remoto
            </a>
        </li>
        {% endif %}
        {% endblock %}



    </ul>
</div>


{% if mostrar_barra_aviso_verde %}
<div class="alert alert-dismissible fade show py-2 barra-avisos-verde" role="alert">
    {% block barra_avisos_verde %}
    {% endblock %}

    {% if alteracoes_sucesso %}
        <p>Alterações realizadas com sucesso</p>
    {% endif %}

    {% if criado_com_sucesso %}
        <p>Foi criado com sucesso</p>
    {% endif %}

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

{% if mostrar_barra_aviso_vermelha %}
<div class="alert alert-dismissible fade show py-2 barra-avisos-vermelha" role="alert">
    {% block barra_avisos_vermelha %}
    {% endblock %}

    {% if informacoes_invalidas %}
        <p>Informações inválidas. Não foi salvo.</p>
    {% endif %}

    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}


<div class="page-content p-5" id="content">

    {% block corpo_pagina %}
    {% endblock %}
</div>



<script type="text/javascript">
    {% block javascript %}
    {% endblock %}
</script>

</body>

</html>

src/usuarios/templates/usuarios/pagina_criar_conta.html
{% extends "usuarios/base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block formulario %}

<div class="jumbotron">
    <h1 class="display-4">Criar uma conta</h1>

    <p class="lead">Preencha os campos abaixo para criar uma conta.</p>

    <form method="POST">
        {% csrf_token %}
{#        {{ formulario.nome|as_crispy_field }}#}
{#        {{ formulario.matricula|as_crispy_field }}#}
{#        {{ formulario.email|as_crispy_field }}#}
{#        {{ formulario.senha|as_crispy_field }}#}
        {{ formulario|crispy }}

        <p>Os campos marcados com "*" são obrigatórios.</p>

        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                <input type="submit" role="button" class="btn btn-danger" value="Criar conta">
                <a href="{% url "pagina_entrar" %}" class="btn btn-primary" role="button">Voltar</a>
            </div>
        </div>
    </form>
</div>



{% endblock %}

{% block javascript %}
    <script>
      $(function(){
        $('form.uniForm').uniform();
      });
    </script>
{% endblock %}

src/usuarios/templates/usuarios/pagina_entrar.html
{% extends "usuarios/base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block formulario %}

    <div class="card text-center" style="width: 300px; margin:0 auto;">
        <div class="card-title bg-secondary">
            <h3 class="py-3" style="color: white">Sistema Sentinela</h3>
        </div>

        <div class="card-body">
            <img class="mb-4" src="{% static 'icones/logo_entrada.png' %}" alt="" width="200">
	    {#<img class="mb-4" src="{% static 'icones/sentinela_logo.svg' %}" alt="" width="200">#}
            <form method="POST" class="form-signin">
                {% csrf_token %}
                {{ formulario_entrar|crispy }}
                <div class="form-row">
                    <div class="form-group center col-md-12 mb-0">
                        <input type="submit" role="button" class="btn btn-primary" value="Entrar">
                        <a href="{% url "pagina_criar_conta" %}" class="btn btn btn-danger" role="button">Criar conta</a>
                    </div>
                </div>
            </form>
        </div>

        <div class="card-footer">
            <img src="{% static 'icones/django-powered.png' %}">
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
         document.getElementById("id_prontuario").focus();
    </script>
{% endblock %}