src/educacao/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'educacao'

urlpatterns = [
    path(
        '',
        login_required(views.Index.as_view()),
        name='index'
    ),
    path(
        '<int:id_disciplina>',
        login_required(views.Index.as_view()),
        name='index'
    ),
    path(
        'criar/disciplina/',
        login_required(views.CriarDisciplina.as_view()),
        name='criar_disciplina'
    ),
    path(
        'inscrever/disciplina/<int:id_disciplina>/',
        login_required(views.InscreverNaDisciplina.as_view()),
        name='matricular_na_disciplina'
    ),
    path(
        'editar/disciplina/<int:id_disciplina>/',
        (views.EditarDisciplina.as_view()),
        name='editar_disciplina'
    ),
    path(
        'ver/disciplina/<int:id_disciplina>/',
        login_required(views.VerDisciplina.as_view()),
        name='ver_disciplina'
    ),
    path(
        'ver/aula/<int:id_aula>/',
        login_required(views.VerAula.as_view()),
        name='ver_aula'
    ),
    path(
        'editar/aula/<int:id_aula>/',
        login_required(views.EditarAula.as_view()),
        name='editar_aula'
    ),
    path(
        'criar/artigo/<int:id_aula>/',
        login_required(views.CriarArtigo.as_view()),
        name='criar_artigo'
    ),
    path(
        'editar/artigo/<int:id_artigo>/',
        login_required(views.EditarArtigo.as_view()),
        name='editar_artigo'
    ),
    path(
        'ver/artigo/<int:id_artigo>/',
        login_required(views.VerArtigo.as_view()),
        name='ver_artigo'
    ),
    path(
        'criar/lista-exercicios/disciplina/<int:id_disciplina>/',
        login_required(views.CriarListaExercicios.as_view()),
        name='criar_lista_exercicios'
    ),
    path(
        'criar/relatorio/disciplina/<int:id_disciplina>/',
        login_required(views.CriarRelatorio.as_view()),
        name='criar_relatorio'
    ),
    path(
        'editar/relatorio/<int:id_relatorio>/',
        login_required(views.EditarRelatorio.as_view()),
        name='editar_relatorio'
    ),
    path(
        'responder/relatorio/<int:id_relatorio>/',
        login_required(views.ResponderRelatorio.as_view()),
        name='responder_relatorio'
    ),
    path(
        'criar/experimento/relatorio/<int:id_relatorio>/',
        login_required(views.AdicionarExperimentoRemotoNoRelatorio.as_view()),
        name='adicionar_experimento_remoto_no_relatorio'
    ),
    path(
        'remover/experimento/relatorio/<int:id_experimento>/',
        login_required(views.RemoverExperimentoNoLabRemoto.as_view()),
        name='remover_experimento_remoto_no_relatorio'
    ),
    path(
        'ver/experimento/<int:id_experimento>/',
        login_required(views.VerExperimento.as_view()),
        name='ver_experimento'
    ),
    path(
        'criar/execucao/<int:id_experimento>/',
        login_required(views.CriarExecucao.as_view()),
        name='criar_execucao'
    ),
    path(
        'duplicar/execucao/<int:id_experimento>/<int:id_execucao>/',
        login_required(views.DuplicarExecucao.as_view()),
        name='duplicar_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.VerExecucao.as_view()),
        name='ver_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/codigo/',
        login_required(views.VerCodigoExecucao.as_view()),
        name='ver_codigo_execucao'
    ),
    path(
        'ver/experimento/<int:id_experimento>/execucao/<int:id_execucao>/grafico/',
        login_required(views.VerGrafico.as_view()),
        name='ver_grafico'
    ),
    path(
        'criar/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.EditarExecucao.as_view()),
        name='editar_execucao'
    ),
    path(
        'executar/experimento/<int:id_experimento>/execucao/<int:id_execucao>/',
        login_required(views.ExecutarExperimento.as_view()),
        name='executar_experimento'
    ),
    path(
        'configurar/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarConfiguracoesAvaliacao.as_view()),
        name='editar_configuracoes_avaliacao'
    ),
    path(
        'editar/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarQuestaoAvaliacao.as_view()),
        name='editar_questao_avaliacao'
    ),
    path(
        'editar/questao/<int:id_questao_avaliacao>/avaliacao/<int:id_avaliacao>/',
        login_required(views.EditarQuestaoAvaliacao.as_view()),
        name='editar_questao_avaliacao'
    ),
    path(
        'editar/avaliacao/<int:id_avaliacao>/criar-nova-questao/',
        login_required(views.AdicionarQuestaoNaAvaliacao.as_view()),
        name='adicionar_questao_avaliacao'
    ),
    path(
        'editar/remover-questao/<int:id_questao_avaliacao>/',
        login_required(views.RemoverQuestaoAvaliacao.as_view()),
        name='remover_questao_avaliacao'
    ),
    path(
        'editar/questao/<int:id_questao_avaliacao>/criar-nova-alternativa/',
        login_required(views.AdicionarAlternativaNaQuestaoDaLista.as_view()),
        name='adicionar_alternativa_questao_avaliacao'
    ),
    path(
        'responder/lista-exercicios/<int:id_avaliacao>/',
        login_required(views.ResponderQuestaoListaExercicios.as_view()),
        name='responder_questao_da_avaliacao'
    ),
    path(
        'responder/questao/<int:id_questao_avaliacao>/lista-exercicios/<int:id_avaliacao>/',
        login_required(views.ResponderQuestaoListaExercicios.as_view()),
        name='responder_questao_da_avaliacao'
    ),
    path(
        'adicionar/anexo/<str:onde>/<int:id>/',
        login_required(views.AdicionarAnexo.as_view()),
        name='adicionar_anexo_onde'
    ),
    path(
        'remover/anexo/<str:onde>/<int:id_anexo>/',
        login_required(views.RemoverAnexoOnde.as_view()),
        name='remover_anexo_onde'
    ),
    path(
        'ver/correcao/lista-exercicios/<int:id_lista>/',
        login_required(views.VerCorrecaoAvaliacao.as_view()),
        name='ver_correcao_lista_exercicios'
    ),
    path(
        'ver/entregas/avaliacao/<int:id_avaliacao>/',
        login_required(views.VerEntregasAvaliacao.as_view()),
        name='ver_entregas_avaliacao'
    ),
    path(
        'corrigir/avaliacao/<int:id_avaliacao>/aluno/<int:id_aluno>/',
        login_required(views.CorrigirQuestaoAvaliacao.as_view()),
        name='corrigir_avaliacao_aluno'
    ),
]

src/lab_remoto/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'lab_remoto'

urlpatterns = [
    path(
        '',
        login_required(views.Index.as_view()),
        name='index'
    ),

    path(
        'criar/kit/',
        login_required(views.CriarKit.as_view()),
        name='criar_kit'
    ),

    path(
        'editar/kit/<int:id_kit>/',
        login_required(views.EditarKit.as_view()),
        name='editar_kit'
    ),

    path(
        'remover/kit/<int:id_kit>/',
        login_required(views.RemoverKit.as_view()),
        name='remover_kit'
    ),

    path(
        'criar/ensaio/',
        login_required(views.CriarEnsaio.as_view()),
        name='criar_ensaio'
    ),

    path(
        'remover/ensaio/<int:id_ensaio>/',
        login_required(views.RemoverEnsaio.as_view()),
        name='remover_ensaio'
    ),

    path(
        'editar/ensaio/<int:id_ensaio>/',
        login_required(views.EditarEnsaio.as_view()),
        name='editar_ensaio'
    ),

    path(
        'remover/parametro/<int:id_parametro>/',
        login_required(views.RemoverParametro.as_view()),
        name='remover_parametro'
    ),

    path(
        'editar/executar/ensaio/<int:id_ensaio>/',
        login_required(views.ExecutarEnsaio.as_view()),
        name='executar_ensaio'
    ),
]

src/sistema_gerenciamento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('almoxarifado/', include('almoxarifado.urls')),
    path('educacao/', include('educacao.urls')),
    path('lab_remoto/', include('lab_remoto.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        }),
    ]

src/lab_remoto/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.forms import formset_factory, modelformset_factory
from crispy_forms.helper import FormHelper

from .models import *
from usuarios.models import Usuario


class FormCriaKit(forms.ModelForm):
    class Meta:
        model = KitDidatico
        fields = (
            'nome',
            'descricao',
            'numero',
            'numero_ensaios_para_manutencao',
        )


class FormEditarKit(forms.ModelForm):
    class Meta:
        model = KitDidatico
        exclude = (
            'data_criacao',
            'ocupado',
            'numero_ensaios_realizados',
        )


FormsetParametroDoKit = modelformset_factory(
    ParametroDoKit,
    exclude=(
        'kit',
    ),
    extra=0,
)


class FormCriarEnsaio(forms.ModelForm):
    class Meta:
        model = Ensaio
        fields = (
            'nome',
            'kit',
            'codigo_executavel',
        )


class FormEditarEnsaio(forms.ModelForm):
    class Meta:
        model = Ensaio
        fields = (
            'nome',
            'kit',
            'codigo_executavel',
            'codigo_grafico',
            'agendavel',
            'executavel',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False


FormsetAdicionarParametroParaSerInformado = modelformset_factory(
    ParametroParaSerInformado,
    exclude=(
        'ensaio',
        'pode_ser_removido',
    ),
    extra=0,
)


class FormEditarTagExecucao(forms.ModelForm):
    class Meta:
        model = ExecucaoEnsaio
        fields = (
            'tag',
            'comentario',
        )

        labels = {
            'tag': 'Tag',
            'comentario': 'Comentário',
        }

src/lab_remoto/templates/lab_remoto/criar_ensaio.html
{% extends "lab_remoto/index.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}


{% block bibliotecas %}
    <link rel="stylesheet" type="text/css" href="{% static 'choosen/chosen_v1.8.7/chosen.min.css' %}">
    <script type="text/javascript" charset="utf8" src="{% static 'choosen/chosen_v1.8.7/chosen.jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block barra_horizontal %}
    <li>
        <input type="submit" form="formulario_artigo" role="button" class="btn btn-primary botao-barra-horizontal" value="Salvar">
    </li>

{#    <li>#}
{#        <a href="{% url 'educacao:ver_aula' form.instance.aula.id %}" class="btn btn-warning">Voltar</a>#}
{#    </li>#}
{% endblock %}


{% block corpo_pagina %}
    <div class="card cartao">
        <h5 class="card-header cartao-titulo">
            <img src="{% static 'icones/equipamento.svg' %}">
            Criar Ensaio
        </h5>
        <div class="card-body">
            <form method="post" id="formulario_artigo" enctype="multipart/form-data" class="formulario sem-asterisco">
                {% csrf_token %}
                {{ formulario|crispy }}
            </form>
        </div>
    </div>
{% endblock %}




{% block javascript %}
{% endblock %}

src/lab_remoto/templates/lab_remoto/criar_kit.html
{% extends "lab_remoto/index.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}


{% block bibliotecas %}
    <link rel="stylesheet" type="text/css" href="{% static 'choosen/chosen_v1.8.7/chosen.min.css' %}">
    <script type="text/javascript" charset="utf8" src="{% static 'choosen/chosen_v1.8.7/chosen.jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block barra_horizontal %}
    <li>
        <input type="submit" form="formulario_artigo" role="button" class="btn btn-primary botao-barra-horizontal" value="Salvar">
    </li>

{#    <li>#}
{#        <a href="{% url 'educacao:ver_aula' form.instance.aula.id %}" class="btn btn-warning">Voltar</a>#}
{#    </li>#}
{% endblock %}


{% block corpo_pagina %}
    <div class="card cartao">
        <h5 class="card-header cartao-titulo">
            <img src="{% static 'icones/equipamento.svg' %}">
            Criar Kit Didático
        </h5>
        <div class="card-body">
            <form method="post" id="formulario_artigo" enctype="multipart/form-data" class="formulario sem-asterisco">
                {% csrf_token %}
                {{ formulario|crispy }}
            </form>
        </div>
    </div>
{% endblock %}




{% block javascript %}
{% endblock %}

src/lab_remoto/templates/lab_remoto/editar_ensaio.html
{% extends "lab_remoto/index.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}


{% block bibliotecas %}
    <link rel="stylesheet" type="text/css" href="{% static 'choosen/chosen_v1.8.7/chosen.min.css' %}">
    <script type="text/javascript" charset="utf8"
            src="{% static 'choosen/chosen_v1.8.7/chosen.jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    <script src="https://pagecdn.io/lib/ace/1.4.12/ace.js" crossorigin="anonymous" integrity="sha256-Q9hnBpgBFstzZOr+OKFOWZWfcF5nFXO8Qz48Nmndo6U=" ></script>
{% endblock %}


{% block barra_horizontal %}
    <li>
        <input type="submit"
               form="formulario_conf_ensaio"
               role="button"
               class="btn btn-primary botao-barra-horizontal"
               value="Salvar"
               name="apenas_salvar"
        >

        <input type="submit"
               form="formulario_conf_ensaio"
               role="button"
               class="btn btn-info botao-barra-horizontal"
               value="Salvar e adicionar parâmetro"
               name="salvar_e_criar_novo_parametro"
        >
    </li>

    {#    <li>#}
    {#        <a href="{% url 'educacao:ver_aula' form.instance.aula.id %}" class="btn btn-warning">Voltar</a>#}
    {#    </li>#}
{% endblock %}


{% block corpo_pagina %}
    <div class="card cartao">
        <h5 class="card-header cartao-titulo">
            <img src="{% static 'icones/equipamento.svg' %}">
            Editar Ensaio
        </h5>
        <div class="card-body">
            <form method="post" id="formulario_conf_ensaio" enctype="multipart/form-data"
                  class="formulario sem-asterisco">
                {% csrf_token %}

                <div class="card cartao">
                    <h5 class="card-header">
                        Sobre o ensaio
                    </h5>
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-6 mb-0">
                                {{ formulario.nome|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                {{ formulario.kit|as_crispy_field }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-inline col-md-6 mb-0">
                                <div class="form-check">
                                    <div class="form-check-input">{{ formulario.agendavel|as_crispy_field }}</div>
                                    <div class="form-check-label">Os estudantes podem criar execuções?</div>
                                </div>
                            </div>
                            <div class="form-inline col-md-6 mb-0">
                                <div class="form-check">
                                    <div class="form-check-input">{{ formulario.executavel|as_crispy_field }}</div>
                                    <div class="form-check-label">Os estudantes podem agendar/executar ensaios?</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="card cartao">
                    <h5 class="card-header">
                        Parâmetros do kit
                    </h5>
                    <div class="card-body">
                        <p>
                            Esses parâmetros são substituídos no código. Para utilizá-los insira a seguinte notação
                            no código: ${sigla} e então esse texto será substituído pelo valor.
                        </p>
                        <p>
                            Exemplo: suponha que Kenc é um parâmetro do sistema que representa o ganho do encoder e
                            vale 3,1415. Para utilizá-lo no código faça:
                        </p>
                        <p>
                            ganho_encoder = ${Kenc}
                        </p>


                        {% for parametro in parametros_kit %}
                        <ul class="list-group list-group-horizontal-xl">
                            <li class="list-group-item"><b>Nome:</b> {{ parametro.nome }}</li>
                            <li class="list-group-item"><b>Sigla:</b> {{ parametro.sigla }}</li>
                            <li class="list-group-item"><b>Valor:</b> {{ parametro.valor }} {{ parametro.unidade }}</li>
                        </ul>
                       {% endfor %}
                    </div>
                </div>

                <div class="card cartao">
                    <h5 class="card-header">
                        Código do ensaio
                    </h5>
                    <div class="card-body">
                        Instruções:

                        <ul>
                            <li>A placa biblioteca da placa será carregada automaticamente</li>
                            <li>
                                A comunicação com a placa é iniciada automaticamente, sendo criado um objeto chamado
                                "placa"
                            </li>
                            <li>
                                Será criado um dicionário com nome "dados" para armazenar as variáveis que devem ser
                                salvas no arquivo matlab. Desse modo você só precisa preencher o dicionário
                            </li>
                            <li>
                                O arquivo matlab é salvo automaticamente ao final do ensaio, não sendo necessário
                                criar esse arquivo
                            </li>
                            <li>
                                A comunicação com a placa é automaticamente encerrada ao final do ensaio
                            </li>
                        </ul>

                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0" id="editor_codigo">
                                {{ formulario.codigo_executavel|as_crispy_field }}
                            </div>
                        </div>
                    </div>
                </div>


                <div class="card cartao">
                    <h5 class="card-header">
                        Código para geração do gráfico
                    </h5>
                    <div class="card-body">
                        Instruções:

                        <ul>
                            <li></li>
                        </ul>

                        <div class="form-row">
                            <div class="form-group col-md-12 mb-0">
                                {{ formulario.codigo_grafico|as_crispy_field }}
                            </div>
                        </div>
                    </div>
                </div>


                <div class="card cartao">
                    <h5 class="card-header">
                        Parâmetros a serem informados pelos estudates
                    </h5>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset %}
                            <div class="form-group form-row">
                                <div class="col-md-4">
                                    {{ form.nome|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.sigla|as_crispy_field }}
                                </div>
                                <div class="col-md-2">
                                    {{ form.valor_minimo|as_crispy_field }}
                                </div>
                                <div class="col-md-2">
                                    {{ form.valor_maximo|as_crispy_field }}
                                </div>

                                {% if form.instance.pode_ser_removido %}
                                <div class="form-check col-md-1">
                                    <a class="btn btn-danger" style="width: 40px; margin-top: 32px" href="{% url 'lab_remoto:remover_parametro' form.instance.id %}" role="button">
                                        X
                                    </a>
                                </div>
                                {% endif %}

                                <div class="row spacer"></div>

                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                </div>


            </form>
        </div>
    </div>


{% endblock %}




{% block javascript %}
    $(document).ready(function(){

		 $('textarea').each(function (i, el) {
			var $el = $(el);

			var $container = $('<div/>').css({
                    position: 'relative',
                    height: 600,
                }).insertAfter(el);

			$el.hide();

			var editor = ace.edit($container[0]);
			editor.setTheme('ace/theme/chrome');
			editor.getSession().setMode("ace/mode/python");
			editor.getSession().setValue($el.val());

            editor.setOptions({
                fontSize: "14pt",
            });

			editor.getSession().on('change', function () {
                    $el.val(editor.getSession().getValue());

                });

			editor.getSession().setUseWrapMode(true);

		 });
    });

{% endblock %}

src/lab_remoto/templates/lab_remoto/editar_kit.html
{% extends "lab_remoto/index.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}


{% block bibliotecas %}
    <link rel="stylesheet" type="text/css" href="{% static 'choosen/chosen_v1.8.7/chosen.min.css' %}">
    <script type="text/javascript" charset="utf8" src="{% static 'choosen/chosen_v1.8.7/chosen.jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block barra_horizontal %}
    <li>
        <input type="submit"
               form="formulario_conf_kit"
               role="button"
               class="btn btn-primary botao-barra-horizontal"
               value="Salvar"
               name="apenas_salvar"
        >

        <input type="submit"
               form="formulario_conf_kit"
               role="button"
               class="btn btn-info botao-barra-horizontal"
               value="Salvar e adicionar parâmetro"
               name="salvar_e_criar_novo_parametro"
        >
    </li>

{#    <li>#}
{#        <a href="{% url 'educacao:ver_aula' form.instance.aula.id %}" class="btn btn-warning">Voltar</a>#}
{#    </li>#}
{% endblock %}


{% block corpo_pagina %}
    <div class="card cartao">
        <h5 class="card-header cartao-titulo">
            <img src="{% static 'icones/equipamento.svg' %}">
            Criar Kit Didático
        </h5>
        <div class="card-body">
            <form method="post" id="formulario_conf_kit" enctype="multipart/form-data" class="formulario sem-asterisco">
                {% csrf_token %}
                {{ formulario_confs_kit|crispy }}

                <h5>Parâmetros do kit</h5>
                {{ formset.management_form }}
                {% for form in formset %}
                    <div class="form-group form-row" style="background-color: #dddddd; border-radius: 5px">
                        <div class="col-md-4">
                            {{ form.nome|as_crispy_field }}
                        </div>
                        <div class="col-md-3">
                            {{ form.sigla|as_crispy_field }}
                        </div>
                        <div class="col-md-2">
                            {{ form.valor|as_crispy_field }}
                        </div>
                        <div class="col-md-2">
                            {{ form.unidade|as_crispy_field }}
                        </div>

                        <div class="form-check col-md-1">
                            <a class="btn btn-danger" style="width: 40px; margin-top: 32px" href="{% url 'lab_remoto:remover_parametro' form.instance.id %}" role="button">
                                X
                            </a>
                        </div>

                        <div class="row spacer"></div>

                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    </div>
                {% endfor %}
            </form>
        </div>
    </div>
{% endblock %}




{% block javascript %}
{% endblock %}

src/lab_remoto/templates/lab_remoto/index.html
{% extends "usuarios/index.html" %}
{% load staticfiles %}

{% block bibliotecas %}

{% endblock %}

{% block barra_horizontal %}
    {% if usuario.tipo == usuario.TIPO_DOCENTE %}
    <li>
        <a class="btn btn-secondary botao-barra-horizontal" href="{% url 'lab_remoto:criar_kit' %}">
            <span><img src="{% static 'icones/novo.svg'%}" width="20px"></span>Adicionar kit
        </a>
    </li>

    <li>
        <a class="btn btn-secondary botao-barra-horizontal" href="{% url 'lab_remoto:criar_ensaio' %}">
            <span><img src="{% static 'icones/novo.svg'%}" width="20px"></span>Criar ensaio
        </a>
    </li>
    {% endif %}

{#    <li>#}
{#        <a class="btn btn-secondary botao-barra-horizontal" href="#">#}
{#            <span><img src="{% static 'icones/apagar.svg'%}" width="20px"></span>Remover#}
{#        </a>#}
{#    </li>#}
{% endblock %}


{% block barra_avisos_verde %}
    {% if alguma_coisa %}
        <p>texto</p>
    {% endif %}
{% endblock %}

{% block barra_avisos_vermelha %}
    {% if alguma_coisa %}
        <p>texto</p>
    {% endif %}
{% endblock %}


{% block corpo_pagina %}
    <div class="row">
        <div class="col-lg-12">

            {% if usuario.tipo == usuario.TIPO_DOCENTE %}

                <div class="card cartao">
                    <h5 class="card-header cartao-titulo">
                        <img src="{% static "icones/equipamento.svg" %}">
                        Kits didáticos
                    </h5>
                    <div class="card-body">
                        <p class="card-title">
                            {% for kit in kits_didaticos %}
                                <ul class="list-group list-group-horizontal-xl">
                                    <li class="list-group-item">{{ kit.nome }} (#{{ kit.numero }})</li>
                                    <li class="list-group-item">
                                        <a href="{% url 'lab_remoto:editar_kit' kit.id %}" class="btn btn-outline-secondary botao-cartao">
                                            <img src="{% static 'icones/editar.svg'%}" width="20px">
                                            Editar
                                        </a>
                                    </li>
                                    <li class="list-group-item">
                                        <a href="{% url 'lab_remoto:remover_kit' kit.id %}" class="btn btn-outline-secondary botao-cartao">
                                            <img src="{% static 'icones/apagar.svg'%}" width="20px">
                                            Remover
                                        </a>
                                    </li>
                                </ul>
                            {% endfor %}
                        </p>
                    </div>
                </div>

                <div class="card cartao">
                    <h5 class="card-header cartao-titulo">
                        <img src="{% static "icones/calculando.svg" %}">
                        Ensaios
                    </h5>
                    <div class="card-body">
                        <p class="card-title">
                            {% for ensaio in ensaios %}
                                {{ ensaio.nome }} (#{{ ensaio.numero }})
                                <a href="{% url 'lab_remoto:editar_ensaio' ensaio.id %}" class="btn btn-outline-secondary botao-cartao">
                                    <img src="{% static 'icones/editar.svg'%}" width="20px">
                                    Editar
                                </a>
                                <a href="{% url 'lab_remoto:remover_kit' ensaio.id %}" class="btn btn-outline-secondary botao-cartao">
                                    <img src="{% static 'icones/apagar.svg'%}" width="20px">
                                    Remover
                                </a>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            {% endif %}


        </div>

        <div class="col-lg-6">
        </div>
    </div>
{% endblock %}




{% block javascript %}
{% endblock %}